# Generated by Django 5.1 on 2024-08-17 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ventas', '0003_alter_cliente_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.ManyToManyField(blank=True, related_name='productos', to='Ventas.categoriaproducto'),
        ),
    ]
